version: "3.8"

services:
  postgres:
    build:
      context: ../postgres
      dockerfile: Dockerfile.dev
    container_name: meatmetrics-postgres-dev
    environment:
      POSTGRES_DB: meatmetrics
      POSTGRES_USER: meatmetrics
      POSTGRES_PASSWORD: meatmetrics123
    ports:
      - "15432:5432"
    volumes:
      - postgres16_data:/var/lib/postgresql/data
      - ../init:/docker-entrypoint-initdb.d
    networks:
      - meatmetrics-network

  backend:
    build:
      context: ../../../backend
      dockerfile: ../infrastructure/docker/backend/Dockerfile.dev
    container_name: meatmetrics-backend-dev
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/meatmetrics
      SPRING_DATASOURCE_USERNAME: meatmetrics
      SPRING_DATASOURCE_PASSWORD: meatmetrics123
      SERVER_PORT: 8080
      # JWT設定（Docker開発環境用）
      JWT_SECRET_KEY: Docker_Dev_MeatMetrics_JWT_Secret_Key_2024_Must_Be_At_Least_256_Bits_For_HS256_Security
      JWT_ACCESS_TOKEN_EXPIRATION_MS: 3600000
      JWT_REFRESH_TOKEN_EXPIRATION_MS: 604800000
    volumes:
      - ../../../backend:/app
      - maven_cache:/root/.m2
    depends_on:
      - postgres
    ports:
      - "8081:8080"
    networks:
      - meatmetrics-network

  frontend:
    build:
      context: ../../../frontend
      dockerfile: ../infrastructure/docker/frontend/Dockerfile.dev
    container_name: meatmetrics-frontend-dev
    environment:
      VITE_PROXY_TARGET: http://backend:8080
    volumes:
      - ../../../frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    networks:
      - meatmetrics-network

volumes:
  postgres16_data:
  maven_cache:

networks:
  meatmetrics-network:
    driver: bridge
