version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: meatmetrics-postgres
    environment:
      POSTGRES_DB: meatmetrics
      POSTGRES_USER: meatmetrics
      POSTGRES_PASSWORD: meatmetrics123
    ports:
      - "15432:5432"
    volumes:
      - postgres16_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
    restart: unless-stopped

volumes:
  postgres16_data:
